M48
; DRILL file {KiCad (6.0.7)} date Fri Dec  2 15:18:27 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-12-02T15:18:27+11:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1063
%
G90
G05
T1
X1.6929Y-5.6299
X1.6929Y-6.5354
X2.6772Y-3.7795
X4.0551Y-3.7795
T0
M30
